# Data Analysis Techniques. Lab 4. Introduction to `pandas`

**Name:** Amin Asylbyek

# **THE TASKS DONE ARE AT THE BOTTOM OF THE FILE**

## 1. `pandas` data structures

The basic data structures in the pandas library are the dataframe, an object of type `DataFrame`, and the series, `Series`, which constitutes a single column of a dataframe. Underlying these structures are NumPy arrays, which we have already encountered in previous classes. Each column in a dataframe is defined by the data type stored in it, including cases where missing values can also be stored (the `Nan` type—not a number).

### 1.1 Pandas `DataFrame` and `series` initialization

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In pandas, a DataSeries is a structure that, in addition to data in the form of a vector, also contains an index, which can be of any type, provided it is a hashable type in Python. Below are a few examples of how to initialize a DataSeries.

In [3]:
# How to view the docstring for the pandas.Series class without having to search for it online
print(pd.Series.__doc__)

    One-dimensional ndarray with axis labels (including time series).

    Labels need not be unique but must be a hashable type. The object
    supports both integer- and label-based indexing and provides a host of
    methods for performing operations involving the index. Statistical
    methods from ndarray have been overridden to automatically exclude
    missing data (currently represented as NaN).

    Operations between Series (+, -, /, \*, \*\*) align values based on their
    associated index values-- they need not be the same length. The result
    index will be the sorted union of the two indexes.

    Parameters
    ----------
    data : array-like, Iterable, dict, or scalar value
        Contains data stored in Series. If data is a dict, argument order is
        maintained.
    index : array-like or Index (1d)
        Values must be hashable and have the same length as `data`.
        Non-unique index values are allowed. Will default to
        RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
        and index is None, then the keys in the data are used as the index. If the
        index is not None, the resulting Series is reindexed with the index values.
    dtype : str, numpy.dtype, or ExtensionDtype, optional
        Data type for the output Series. If not specified, this will be
        inferred from `data`.
        See the :ref:`user guide <basics.dtypes>` for more usages.
    name : Hashable, default None
        The name to give to the Series.
    copy : bool, default False
        Copy input data. Only affects Series or 1d ndarray input. See examples.

    Notes
    -----
    Please reference the :ref:`User Guide <basics.series>` for more information.

    Examples
    --------
    Constructing Series from a dictionary with an Index specified

    >>> d = {'a': 1, 'b': 2, 'c': 3}
    >>> ser = pd.Series(data=d, index=['a', 'b', 'c'])
    >>> ser
    a   1
    b   2
    c   3
    dtype: int64

    The keys of the dictionary match with the Index values, hence the Index
    values have no effect.

    >>> d = {'a': 1, 'b': 2, 'c': 3}
    >>> ser = pd.Series(data=d, index=['x', 'y', 'z'])
    >>> ser
    x   NaN
    y   NaN
    z   NaN
    dtype: float64

    Note that the Index is first build with the keys from the dictionary.
    After this the Series is reindexed with the given Index values, hence we
    get all NaN as a result.

    Constructing Series from a list with `copy=False`.

    >>> r = [1, 2]
    >>> ser = pd.Series(r, copy=False)
    >>> ser.iloc[0] = 999
    >>> r
    [1, 2]
    >>> ser
    0    999
    1      2
    dtype: int64

    Due to input data type the Series has a `copy` of
    the original data even though `copy=False`, so
    the data is unchanged.

    Constructing Series from a 1d ndarray with `copy=False`.

    >>> r = np.array([1, 2])
    >>> ser = pd.Series(r, copy=False)
    >>> ser.iloc[0] = 999
    >>> r
    array([999,   2])
    >>> ser
    0    999
    1      2
    dtype: int64

    Due to input data type the Series has a `view` on
    the original data, so
    the data is changed as well.

**Example 1**

In [4]:
# initialization of an empty pandas series
series_1 = pd.Series()
series_1

Series([], dtype: object)

In [5]:
# main descriptive statistics, we can run this function for a DataFrame
series_1.describe()

count       0
unique      0
top       NaN
freq      NaN
dtype: object

**Example 2**

In [6]:
data = np.arange(1,6)
series_2 = pd.Series(data)
series_2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
# now we can see more as we have a numerical series
series_2.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

**Example 3**

In [8]:
# pandas series from a Python dictionary
data = {key: val for key,val in zip('abcd',[1,2,3,4])}
print(f"Dict: {data}")
series_3 = pd.Series(data)
series_3

Dict: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
series_3.index

Index(['a', 'b', 'c', 'd'], dtype='object')

**Example 4**

In [10]:
# we can convert pandas series to a python list
# methods tolist() and to_list()
series_3.tolist()

[1, 2, 3, 4]

In [11]:
series_3.index.tolist()

['a', 'b', 'c', 'd']

**Example 5**

In [12]:
# Looking at the docstring for Series, we can see that arithmetic operations on data series are also possible
# provided that certain rules are followed (the length of the data series vector)
series_3 + series_3

a    2
b    4
c    6
d    8
dtype: int64

In [13]:
series_3 ** 2

a     1
b     4
c     9
d    16
dtype: int64

In [14]:
series_3

a    1
b    2
c    3
d    4
dtype: int64

**Example 6**

In [15]:
# We can also take advantage of certain features of the NumPy library related to returning copies and views of arrays
# Below is an example showing how to create a data series that is a view of a NumPy array
arr = np.arange(1, 6)
print(arr)
series_4 = pd.Series(arr, copy=False)
series_4

[1 2 3 4 5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
# The `values` attribute returns the series data as a NumPy array
# We compare the addresses of both arrays—if they match, they point to the same memory location
series_4.values.base == arr.base

True

In [17]:
# This allows us to share this memory, along with all its benefits
# and drawbacks (less memory allocated, but no data isolation
# in the event of modifications made through any of the views)

# Modifying the variable naturally updates its value across all views
arr[0] = 99
print(arr)
print(series_4)

[99  2  3  4  5]
0    99
1     2
2     3
3     4
4     5
dtype: int64

**Example 7**

In [18]:
# You can name a data series, although this is not often done in practice
series_4.name = "age"
series_4

0    99
1     2
2     3
3     4
4     5
Name: age, dtype: int64

**Example 8**

In [19]:
# We generate a time series using the `date_range(start, number_of_periods, interval)` function
timeseries = pd.date_range('2025-03-20 12:00:00', periods=6, freq='h')
timeseries

DatetimeIndex(['2025-03-20 12:00:00', '2025-03-20 13:00:00',
               '2025-03-20 14:00:00', '2025-03-20 15:00:00',
               '2025-03-20 16:00:00', '2025-03-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [20]:
# The pandas series also has a special index type for time series data
# Here we'll generate such data, but it can also be loaded from files
data = [f'event {n}' for n in range(1, 7)]
timeseries = pd.Series(data, index=timeseries)
timeseries

2025-03-20 12:00:00    event 1
2025-03-20 13:00:00    event 2
2025-03-20 14:00:00    event 3
2025-03-20 15:00:00    event 4
2025-03-20 16:00:00    event 5
2025-03-20 17:00:00    event 6
Freq: h, dtype: object

In [21]:
timeseries.index

DatetimeIndex(['2025-03-20 12:00:00', '2025-03-20 13:00:00',
               '2025-03-20 14:00:00', '2025-03-20 15:00:00',
               '2025-03-20 16:00:00', '2025-03-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

**DataFrame initialization**

Just as with data series, we can convert other data structures into a data frame, provided certain conditions are met. Let’s start with a list.

**Example 9**

In [22]:
df_1 = pd.DataFrame([f'row {n}' for n in range(1, 6)])
df_1

       0
0  row 1
1  row 2
2  row 3
3  row 4
4  row 5

In [23]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      object
dtypes: object(1)
memory usage: 172.0+ bytes

In [24]:
df_1.describe()

            0
count       5
unique      5
top     row 1
freq        1

In [25]:
print(df_1.ndim, df_1.dtypes, df_1.shape, sep='\n')

2
0    object
dtype: object
(5, 1)

In [26]:
df_1.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
# list of columns in DataFrame
df_1.columns

RangeIndex(start=0, stop=1, step=1)

In [28]:
df_1.columns = ['feature 1']
df_1

  feature 1
0     row 1
1     row 2
2     row 3
3     row 4
4     row 5

**Example 10**

In [29]:
# There are many ways to access data within series and charts
# Here, we are referring to a single column, which, as you can see, is the default axis for searching for this value (column label)
df_1['feature 1']

0    row 1
1    row 2
2    row 3
3    row 4
4    row 5
Name: feature 1, dtype: object

In [30]:
# each column is a pandas series
type(df_1['feature 1'])

pandas.core.series.Series

**Example 11**

In [31]:
# There is an overloaded DataFrame constructor that, among other things, allows you to convert a nested list
# (in this case, a two-level list) into a DataFrame without any additional transformations
nested_list = [[1,2,3,4] for _ in range(4)]
df_2 = pd.DataFrame(nested_list, columns=list('ABCD'))
df_2

   A  B  C  D
0  1  2  3  4
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4

In [32]:
# `describe` works for all numeric columns
df_2.describe()

         A    B    C    D
count  4.0  4.0  4.0  4.0
mean   1.0  2.0  3.0  4.0
std    0.0  0.0  0.0  0.0
min    1.0  2.0  3.0  4.0
25%    1.0  2.0  3.0  4.0
50%    1.0  2.0  3.0  4.0
75%    1.0  2.0  3.0  4.0
max    1.0  2.0  3.0  4.0

**Example 12**

In [33]:
df_2['D'] = df_2['D'].astype(str)
df_2.describe()

         A    B    C
count  4.0  4.0  4.0
mean   1.0  2.0  3.0
std    0.0  0.0  0.0
min    1.0  2.0  3.0
25%    1.0  2.0  3.0
50%    1.0  2.0  3.0
75%    1.0  2.0  3.0
max    1.0  2.0  3.0

**Example 13**

In [34]:
# Initializing a frame from a dictionary—here's a simple example to illustrate the required dictionary format
# Dictionary keys
data_dict = {'label': 'computer', 'price': 1999.0}
df_3 = pd.DataFrame(data_dict, index=list(range(1)))
df_3

      label   price
0  computer  1999.0

**Example 14**

In [35]:
# This is probably not the result we were expecting
df_4 = pd.DataFrame(data_dict, index=list(range(len(data_dict))))
df_4

      label   price
0  computer  1999.0
1  computer  1999.0

**Przykład 15**

In [36]:
# Now it's better - key: list of values
data_dict = {'label': ['computer', 'monitor', 'mouse'], 'price': [1999.0, 299.0, 30]}
df_5 = pd.DataFrame(data_dict)
df_5

      label   price
0  computer  1999.0
1   monitor   299.0
2     mouse    30.0

**Loading Data into a Frame from Files**

A list of available functions for reading and writing data to and from pandas frames can be found in the documentation at: https://pandas.pydata.org/docs/reference/io.html

Examples using selected options are presented below.

File **iris.data** is in the same folder as this notebook.

In [37]:
# Loading data into a frame from a file
# Displaying the first 5 lines from the file (may not work depending on your operating system configuration)
! head -5 iris.data

sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa

**Example 16**

In [38]:
# We read data into a file using the `read_csv` function with default parameters (delimiter, encoding, error handling, header, and others)
df_6 = pd.read_csv('iris.data')
df_6

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [39]:
df_6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sepal length in cm  150 non-null    float64
 1   sepal width in cm   150 non-null    float64
 2   petal length in cm  150 non-null    float64
 3   petal width in cm   150 non-null    float64
 4   class               150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

**Example 17**

In [40]:
df_7 = pd.read_table('iris.data', sep=',')
df_7

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

**Example 18**

In [41]:
# If the file does not have a header row, we can specify this option when loading it
# But first, let's save the data to a CSV file using the to_csv function

# file path, separator, whether to save the header, whether to save the index (if it was created
# while loading data into the frame, we usually don’t want to save it), character encoding
df_7.to_csv('iris.csv', sep=';', header=True, index=False, encoding='utf-8')

In [42]:
# migth not work on Windows
!head -5 iris.csv

sepal length in cm;sepal width in cm;petal length in cm;petal width in cm;class
5.1;3.5;1.4;0.2;Iris-setosa
4.9;3.0;1.4;0.2;Iris-setosa
4.7;3.2;1.3;0.2;Iris-setosa
4.6;3.1;1.5;0.2;Iris-setosa

### Tasks

**Task 1**

Create a data series where the values are integers from 1 to 100 and the indices are in the range from ean_001 to ean_100.

In [43]:
import pandas as pd
import numpy as np

values = np.arange(1, 101)
indices = [f"ean_{i:03d}" for i in range(1, 101)]
series_task1 = pd.Series(values, index=indices)

print(series_task1.head())
print("...")
print(series_task1.tail())

ean_001    1
ean_002    2
ean_003    3
ean_004    4
ean_005    5
dtype: int64
...
ean_096     96
ean_097     97
ean_098     98
ean_099     99
ean_100    100
dtype: int64

**Task 2**

Create a two-dimensional NumPy array of size 10x10, where the values are stored according to the following pattern:
```python
[
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024],
    [3, 9, 27 ... ],
    ...
    [10, 100, 1000, ... ]
]
```
The first column contains a number, which is then squared in the subsequent columns. Define this array as you see fit, but you are not allowed to enter this data “manually.”

Create a Pandas DataFrame from this data. Name the columns according to the pattern [‘base’, ‘pow_2’, ‘pow_3’, ..., ‘pow_10’]

In [44]:
# Create the 10x10 numpy array using broadcasting
bases = np.arange(1, 11).reshape(10, 1)
powers = np.arange(1, 11)
array_10x10 = bases ** powers

# Create column names
columns = ['base'] + [f'pow_{i}' for i in range(2, 11)]

# Create the DataFrame
df_task2 = pd.DataFrame(array_10x10, columns=columns)
print(df_task2)

   base  pow_2  pow_3  pow_4   pow_5    pow_6     pow_7      pow_8  \
0     1      1      1      1       1        1         1          1
1     2      4      8     16      32       64       128        256
2     3      9     27     81     243      729      2187       6561
3     4     16     64    256    1024     4096     16384      65536
4     5     25    125    625    3125    15625     78125     390625
5     6     36    216   1296    7776    46656    279936    1679616
6     7     49    343   2401   16807   117649    823543    5764801
7     8     64    512   4096   32768   262144   2097152   16777216
8     9     81    729   6561   59049   531441   4782969   43046721
9    10    100   1000  10000  100000  1000000  10000000  100000000

        pow_9       pow_10
0           1            1
1         512         1024
2       19683        59049
3      262144      1048576
4     1953125      9765625
5    10077696     60466176
6    40353607    282475249
7   134217728   1073741824
8   387420489   3486784401
9  1000000000  10000000000

**Task 3**

Check whether the NumPy array from the previous task and the pandas frame share the same data. If not, create another frame that shares this data with the array (you can use the method from previous labs to check this).

In [45]:
# Check if they share memory
shares_memory = np.shares_memory(array_10x10, df_task2.values)
print(f"Original DataFrame shares memory with array: {shares_memory}")

# Create a new frame that shares memory
df_shared = pd.DataFrame(array_10x10, columns=columns, copy=False)

# Verify the new frame shares memory
shares_memory_new = np.shares_memory(array_10x10, df_shared.values)
print(f"New DataFrame shares memory with array: {shares_memory_new}")

Original DataFrame shares memory with array: True
New DataFrame shares memory with array: True

**Task 4**

Check the data type assigned to the frame from the previous task. Can it be downcast to a type that preserves the original data but reduces the amount of memory required to store it? Justify your answer with an appropriate code example.

In [46]:
print("Original Data Types:")
print(df_shared.dtypes.head(3))
original_memory = df_shared.memory_usage(deep=True).sum()

# Downcast numerical columns to the smallest unsigned integer type possible
df_downcasted = df_shared.apply(pd.to_numeric, downcast='unsigned')

print("\nDowncasted Data Types:")
print(df_downcasted.dtypes.head(3))
downcasted_memory = df_downcasted.memory_usage(deep=True).sum()

print(f"\nOriginal Memory Usage: {original_memory} bytes")
print(f"Downcasted Memory Usage: {downcasted_memory} bytes")

Original Data Types:
base     int64
pow_2    int64
pow_3    int64
dtype: object

Downcasted Data Types:
base      uint8
pow_2     uint8
pow_3    uint16
dtype: object

Original Memory Usage: 932 bytes
Downcasted Memory Usage: 472 bytes

**Task 5**

Read data from the `iris.data` file using the `read_csv` function into the `iris` variable, as shown in the example.

In [47]:
iris = pd.read_csv('iris.data')
print(iris.head())

   sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4
1                 4.9                3.0                 1.4
2                 4.7                3.2                 1.3
3                 4.6                3.1                 1.5
4                 5.0                3.6                 1.4

   petal width in cm        class
0                0.2  Iris-setosa
1                0.2  Iris-setosa
2                0.2  Iris-setosa
3                0.2  Iris-setosa
4                0.2  Iris-setosa

**Task 6**

Replace the column names in the `iris` frame so that spaces are replaced with the `_` character. Display the first 10 rows of this frame.

In [48]:
iris.columns = iris.columns.str.replace(' ', '_')
print(iris.head(10))

   sepal_length_in_cm  sepal_width_in_cm  petal_length_in_cm  \
0                 5.1                3.5                 1.4
1                 4.9                3.0                 1.4
2                 4.7                3.2                 1.3
3                 4.6                3.1                 1.5
4                 5.0                3.6                 1.4
5                 5.4                3.9                 1.7
6                 4.6                3.4                 1.4
7                 5.0                3.4                 1.5
8                 4.4                2.9                 1.4
9                 4.9                3.1                 1.5

   petal_width_in_cm        class
0                0.2  Iris-setosa
1                0.2  Iris-setosa
2                0.2  Iris-setosa
3                0.2  Iris-setosa
4                0.2  Iris-setosa
5                0.4  Iris-setosa
6                0.3  Iris-setosa
7                0.2  Iris-setosa
8                0.2  Iris-setosa
9                0.1  Iris-setosa

**Task 7**

Use the `memory_usage()` method (with and without the `deep=True` parameter) to check how much memory the frame occupies. Choose one of the float data types with lower precision and store the frame in a new variable `iris_smaller`, whose numeric columns will be cast to this new float type. Check again how much memory has been allocated for the frame.

In [49]:
# Original memory usage
mem_original = iris.memory_usage(deep=True).sum()
print(f"Original memory usage: {mem_original} bytes")

# Downcast float64 to float32
iris_smaller = iris.copy()
float_cols = iris_smaller.select_dtypes(include=['float64']).columns
iris_smaller[float_cols] = iris_smaller[float_cols].astype('float32')

# New memory usage
mem_smaller = iris_smaller.memory_usage(deep=True).sum()
print(f"Memory usage after downcasting to float32: {mem_smaller} bytes")

Original memory usage: 14282 bytes
Memory usage after downcasting to float32: 11882 bytes

**Task 8**

Save the frame to the clipboard (using the `to_clipboard()` function), then paste the clipboard contents into a text editor and any spreadsheet. Check the format of this data.

Now copy a portion of this pasted data to the clipboard and save it to a new frame using the `from_clipboard()` method.
Display the first 5 rows of this clip.

The solution to this task is simply to call the above function; the rest is for the student’s information and knowledge.

In [57]:
# We use a try-except block so it doesn't crash the Colab notebook
try:
    # Attempt to save the first 10 rows to the clipboard
    iris_smaller.head(10).to_clipboard(index=False)
    print("Successfully copied to clipboard.")

    # Attempt to read from the clipboard
    df_from_clip = pd.read_clipboard()
    print("Data from clipboard:")
    print(df_from_clip.head(5))

except Exception as e:
    print("Clipboard functions are not supported in this environment (e.g., Google Colab).")
    print("Error details:", e)
    print("\n--- Simulated Output ---")
    print(iris_smaller.head(5))

Clipboard functions are not supported in this environment (e.g., Google Colab).
Error details:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error


--- Simulated Output ---
   sepal_length_in_cm  sepal_width_in_cm  petal_length_in_cm  \
0                 5.1                3.5                 1.4
1                 4.9                3.0                 1.4
2                 4.7                3.2                 1.3
3                 4.6                3.1                 1.5
4                 5.0                3.6                 1.4

   petal_width_in_cm        class
0                0.2  Iris-setosa
1                0.2  Iris-setosa
2                0.2  Iris-setosa
3                0.2  Iris-setosa
4                0.2  Iris-setosa

**Task 9**

Install the frameworks for the `parquet`, `json`, and `pickle` formats (you may need to install additional packages) using the relevant functions described in the documentation (link provided in the materials).

In [54]:
!pip install pyarrow fastparquet

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Collecting fastparquet
  Downloading fastparquet-2026.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.0.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from fastparquet) (2025.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from fastparquet) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->fastparquet) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Downloading fastparquet-2026.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 23.3 MB/s eta 0:00:00
Installing collected packages: fastparquet
Successfully installed fastparquet-2026.3.0

In [55]:
import pyarrow
import fastparquet
import json
import pickle

print("Libraries for Parquet, JSON, and Pickle are successfully available in your environment.")

Libraries for Parquet, JSON, and Pickle are successfully available in your environment.